### PR TITLE
Remove columns from the top of matrix 

### PR DESCRIPTION
**Pull request by bikramkawan**
Closes https://github.com/Caleydo/taggle/issues/306

### CODE REVIEW

**Comment by NMO13** [comment]
Works basically, however the URL hash won't be updated properly:
bug

**Comment by NMO13** [comment]
@bikramkawan If you want, I'll try to fix it.

**Comment by NMO13** [comment]
Another problem: It is possible that support views have the same CSS class:
image
This is problematic since the removal of a support view relies on a unique class name.

**Comment by bikramkawan** [comment]
We can add the support view id in the end.

**Comment by sgratzl** [comment]
as far as I understood https://github.com/Caleydo/taggle/blob/master/src/SupportView.ts#L51 stores the DOM node for each support view, why not just removing this node instead of searching for it?

**Pull request merged**
