### PR TITLE
Replace data type icons in select2 and side panel

### PR DESCRIPTION
**Pull request by thinkh**
Closes Caleydo/taggle#133.

Using the suggested icons from [Resonat Lab](https://resonantlab.kitware.com/)

**Side panel**

**Select2**

**Minor issue**
I cannot color the icons in the select2, because they are used as background-image in the SCSS file. I found a [svg-fill-loader](https://github.com/kisenka/svg-fill-loader/) for webpack that should solve this problem. However, I couldn't integrate it in the webpack.config.js and run it. If @sgratzl has a few minutes maybe he could have a look into the correct config setting. Afterwards I can adapt the usages in the SCSS.

### CODE REVIEW

**Comment by alexsb** [comment]
These look good. Do we make a distinction between nominal and ordinal in taggle? If so, we should also make the distinction in the icons.

**Comment by mstreit** [comment]
As far as I know, LineUp has no notion of ordinal data.

**Comment by sgratzl** [comment]
what is the status there, since the code essentially moved to lineupjs

**Comment by thinkh** [comment]
I don't know. @sgratzl Did you transfer the new items to LineUp, too?

**Comment by mstreit** [comment]
I think this PR is obsolete and can be deleted.

**Pull request closed without merging**
