### PR TITLE
Aggregated histogram

### PR DESCRIPTION
**Pull request by NMO13**
See https://github.com/Caleydo/taggle/issues/314
Histograms with single bins will be shown as moasic plot with labels.
image

### CODE REVIEW

**Comment by mstreit** [comment]
Looks good! I suggest to use the font size as in the other row-based visualizations (e.g. bar renderer). Same for the aggregated string vis.

**Comment by mstreit** [comment]
Btw, what is the number before the group label?

**Comment by thinkh** [comment]
> Btw, what is the number before the group label?

This the category for this attribute. It's contained like this in the [dataset](https://github.com/Caleydo/taggle/blob/master/data/AIDS_Countries.csv).

**Comment by NMO13** [comment]
Yes its part of the name: 
image

**Comment by NMO13** [comment]
I personally would suggest to make the font size bigger than that in the row based. Because there is enough space and it is easier to read.

**Comment by mstreit** [comment]
re font size: is there enough space? because in the screenshot the labels are cut. as we have additional vertical space left, we could add a line break instead of reducing the font size.

re number in label: ah, yes. I think we added it to the label because it is an ordered categorical attribute (1 < 2 < 3 < 4)

**Comment by NMO13** [comment]
image

**Pull request merged**
